version: '3.4'

services:

  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    ports:
      - "80:80"
    links:
      - resources:resources
      - database:database
    volumes:
      - ./config/dispatcher:/config

  database:
    image: redpencil/virtuoso:1.0.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini

  resources:
    image: semtech/mu-cl-resources:1.20.0
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/besluittypes"

  migrations:
    image: semtech/mu-migrations-service:0.7.0
    volumes:
      - ./config/migrations:/data/migrations
    links:
      - database:database

