(in-package :mu-cl-resources)

(add-prefix "skos"                             "http://www.w3.org/2004/02/skos/core#")
(add-prefix "conceptscheme"                    "https://data.vlaanderen.be/id/conceptscheme/")
(add-prefix "BesluitType"                      "https://data.vlaanderen.be/id/concept/BesluitType/")
(add-prefix "BesluitDocumentType"              "https://data.vlaanderen.be/id/concept/BesluitDocumentType/")
(add-prefix "skos"                             "http://www.w3.org/2004/02/skos/core#")
(add-prefix "xsd"                              "http://www.w3.org/2001/XMLSchema#")
(add-prefix "rdf"                              "http://www.w3.org/1999/02/22-rdf-syntax-ns#")
(add-prefix "core"                             "http://mu.semte.ch/vocabularies/core/")
(add-prefix "besluit"                          "http://lblod.data.gift/vocabularies/besluit/")
(add-prefix "BestuurseenheidClassificatieCode" "http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/")
